version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=pokemon

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokemon
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/src/infrastructure/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: